# Generated by Django 5.1.7 on 2025-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='name',
            field=models.CharField(default='Warsaw to Prague', max_length=100),
            preserve_default=False,
        ),
    ]
