# Generated by Django 5.1.7 on 2025-04-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_backgroundimage_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoutePoint',
            new_name='Point',
        ),
    ]
